### ISSUE TITLE
ImportError: cannot import name 'check_download_model' from 'utils'

### ISSUE THREAD

**Issue by toyxyz** [viperyl/ComfyUI-BiRefNet#19]
Hi! Thanks for the great work as always. I updated ComfyUI and got the following error: When I commented out all 'check_download_model', the error did not occur. 

Traceback (most recent call last):
  File "C:\Comfy\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BiRefNet\__init__.py", line 3, in <module>
    from .BiRefNet_node import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BiRefNet\BiRefNet_node.py", line 7, in <module>
    from models.baseline import BiRefNet
  File "C:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BiRefNet\models\baseline.py", line 11, in <module>
    from models.backbones.build_backbone import build_backbone
  File "C:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BiRefNet\models\backbones\build_backbone.py", line 8, in <module>
    from utils import check_download_model
ImportError: cannot import name 'check_download_model' from 'utils' (C:\Comfy\ComfyUI_windows_portable\ComfyUI\utils\__init__.py)

**Comment by AugmentedRealityCat** [comment]
Pretty much the same error message over here:

```
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BiRefNet\__init__.py", line 3, in <module>
    from .BiRefNet_node import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BiRefNet\BiRefNet_node.py", line 7, in <module>
    from models.baseline import BiRefNet
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BiRefNet\models\baseline.py", line 11, in <module>
    from models.backbones.build_backbone import build_backbone
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BiRefNet\models\backbones\build_backbone.py", line 8, in <module>
    from utils import check_download_model
ImportError: cannot import name 'check_download_model' from 'utils' (D:\ComfyUI_windows_portable\ComfyUI\utils\__init__.py)
```

**Comment by Aljnk** [comment]
build_backbone.py ->
change `from utils import check_download_model` to 
```
import sys
import os
import importlib.util
path = os.path.dirname(os.path.dirname(os.path.dirname(__file__)))
utils_path = os.path.join(path, "utils.py")
spec = importlib.util.spec_from_file_location("utils", utils_path)
utils = importlib.util.module_from_spec(spec)
spec.loader.exec_module(utils)
check_download_model = utils.check_download_model
```

BiRefNet_node.py -> change `from utils import check_download_model` to `from .utils import check_download_model`

work for me :)

**Comment by Aljnk** [comment]
or you can try to rename `\ComfyUI\custom_nodes\ComfyUI-BiRefNet\utils.py` to something unique -> for example `brn_utils.py` and then use `from brn_utils import check_download_model` - may helps too
